name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install semgrep
        run: |
          curl -Lo semgrep.tar.gz https://github.com/returntocorp/semgrep/releases/download/v0.74.0/semgrep-v0.74.0-linux-amd64.tar.gz
          tar -xzf semgrep.tar.gz
          sudo mv semgrep /usr/local/bin/

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        
   
      - name: Run semgrep
        run: semgrep ci
