name: Semgrep Full Scan

on:
  push:
    branches:
      - main


jobs:

  semgrep-full:
      runs-on: ubuntu-latest
      container:
        image: returntocorp/semgrep

      steps:

        # step 1
        - name: clone application source code
          uses: actions/checkout@v3

        #init
        - name: full scan
          run: |
            semgrep ci
          env:
            SEMGREP_APP_TOKEN: ${{secrets.SEM_SECRET}}
   
  eslint-full:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i
      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

  sonarcloud_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      # - name: SonarCloud Scan
      #   run:  mvn -B verify sonar:sonar -Dsonar.projectKey=research_ipsenh_bruno -Dsonar.organization=brunoseriese -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SON_TOKEN
      #   env:
      #     GIT_HUB_TOKEN: ${{ secrets.RES.TOKEN }}
      #     SONARCLOUD_TOKEN: ${{ secrets.SON_TOKEN }}
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=research_ipsenh_bruno
            -Dsonar.organization=brunoseriese
            -Dsonar.host.url=https://sonarcloud.io
            -X # Enable debug logging
        env:
          GITHUB_TOKEN: ${{ secrets.RES_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SON_TOKEN }}