name: Semgrep Full Scan

on:
  push:
    branches:
      - main


jobs:

  semgrep-full:
      runs-on: ubuntu-latest
      container:
        image: returntocorp/semgrep

      steps:

        # step 1
        - name: clone application source code
          uses: actions/checkout@v3

        #init
        - name: full scan
          run: |
            semgrep ci
          env:
            SEMGREP_APP_TOKEN: ${{secrets.SEM_SECRET}}
   
        